### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [MalcolmScruggs/CircoIconPack#9]
Hi,

Since this app is Apache v2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by MalcolmScruggs** [comment]
I think the addition to F-Droid is a great idea. I'll try to take a stab at getting it included myself hopefully in the coming weeks.

If you or someone else wants to work on inclusion right away I'd be happy to support that as well.

**Comment by Poussinou** [comment]
We're understaffed at F-Droid, and it's always better if the original dev include his app himself, so we'll wait for your contribution. You can start by opening a RFP [here](https://gitlab.com/fdroid/rfp/issues), and then push a MR on fdroiddata [here](https://gitlab.com/fdroid/fdroiddata).

**Comment by Poussinou** [comment]
Here you go with the RFP: https://gitlab.com/fdroid/rfp/issues/1223

**Comment by ClockGen** [comment]
Since https://f-droid.org/en/2019/03/26/the-latest-tab-now-highlights-good-descriptions.html we'd like to have "The upstream app source code repo contains the app metadata (summary/description/images/changelog/etc) in a [Fastlane](https://gitlab.com/snippets/1895688) or [Triple-T](https://gitlab.com/snippets/1901490) folder structure" as mentioned in the MR template, can this be realized? (and retag after the modification)
